# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Normal Theme"
license = "MIT"
licenselink = "https://github.com/mfcollins3/website/blob/master/themes/normal/LICENSE"
description = "Normal theme for my personal blog and website"
homepage = "https://www.michaelfcollins3.me"
tags = []
features = []
min_version = "0.80.0"

[author]
  name = "Michael Collins"
  homepage = "https://www.michaelfcollins3.me"
